SELECT * FROM gd_esquema.Maestra

--Tabla Inmueble
CREATE TABLE #Inmueble (
    INMUEBLE_CODIGO INT PRIMARY KEY,
    INMUEBLE_NOMBRE VARCHAR(150),
    INMUEBLE_DESCRIPCION VARCHAR(MAX),
    INMUEBLE_DIRECCION VARCHAR(200),
    INMUEBLE_SUPERFICIETOTAL DECIMAL(10,2),
    INMUEBLE_ANTIGUEDAD INT,
    INMUEBLE_EXPESAS DECIMAL(10,2),
    INMUEBLE_BARRIO CHAR(25), -- FK
    INMUEBLE_LOCALIDAD CHAR(25), -- FK
    INMUEBLE_PROVINCIA CHAR(25), -- FK
    INMUEBLE_TIPO_INMUEBLE CHAR(25), -- FK
    INMUEBLE_CANT_AMBIENTES CHAR(25), -- FK
    INMUEBLE_ORIENTACION CHAR(25), -- FK
    INMUEBLE_DISPOSICION CHAR(25), -- FK
	PROPIETARIO_DNI INT --FK
);

-- Tabla Propietario
CREATE TABLE #Propietario (
    PROPIETARIO_DNI INT PRIMARY KEY,
    PROPIETARIO_NOMBRE VARCHAR(100),
    PROPIETARIO_APELLIDO VARCHAR(100),
    PROPIETARIO_FECHA_REGISTRO DATE,
    PROPIETARIO_TELEFONO VARCHAR(20),
    PROPIETARIO_MAIL VARCHAR(100),
    PROPIETARIO_FECHA_NAC DATE
);

-- Tabla Anuncio
CREATE TABLE #Anuncio (
    ANUNCIO_CODIGO INT PRIMARY KEY,
    ANUNCIO_FECHA_PUBLICACION DATE,
    ANUNCIO_PRECIO_PUBLICADO DECIMAL(10,2),
    ANUNCIO_COSTO_ANUNCIO DECIMAL(10,2),
    ANUNCIO_FECHA_FINALIZACION DATE,
    ANUNCIO_TIPO_OPERACION CHAR(25), -- FK
    ANUNCIO_MONEDA CHAR(25), -- FK
    ANUNCIO_ESTADO CHAR(25), -- FK
	ANUNCIO_AGENTE INT, --FK INT,
    ANUNCIO_TIPO_PERIODO CHAR(25), -- FK
	INMUEBLE_CODIGO INT -- FK
);

-- Tabla Agente
CREATE TABLE #Agente (
    AGENTE_DNI INT PRIMARY KEY,
    AGENTE_NOMBRE VARCHAR(100),
    AGENTE_APELLIDO VARCHAR(100),
    AGENTE_FECHA_REGISTRO DATE,
    AGENTE_TELEFONO VARCHAR(20),
    AGENTE_MAIL VARCHAR(100),
    AGENTE_FECHA_NAC DATE,
	SUCURSAL_CODIGO INT --FK
);

-- Tabla Sucursal
CREATE TABLE #Sucursal (
    SUCURSAL_CODIGO INT PRIMARY KEY,
    SUCURSAL_NOMBRE VARCHAR(100),
    SUCURSAL_DIRECCION VARCHAR(200),
    SUCURSAL_TELEFONO VARCHAR(20),
    SUCURSAL_LOCALIDAD CHAR(25), -- FK
    SUCURSAL_PROVINCIA CHAR(25) -- FK
);

-- Tabla Caracteristica
CREATE TABLE #Caracteristica (
    CARACTERISTICA CHAR(25) PRIMARY KEY,
);

-- Tabla Inmueble_caracteristica (Relación entre Inmueble y Caracteristica)
CREATE TABLE #Inmueble_caracteristica (
    INMUEBLE_ID INT, -- FK
    CARACTERISTICA CHAR(25), -- FK
	 PRIMARY KEY (INMUEBLE_ID, CARACTERISTICA)
);

-- Tabla Venta
CREATE TABLE #Venta (
    VENTA_CODIGO INT PRIMARY KEY,
	ANUNCIO_CODIGO INT, -- FK
    VENTA_FECHA DATE,
    VENTA_PRECIO_VENTA DECIMAL(10,2),
    VENTA_COMISION DECIMAL(10,2),
    VENTA_MONEDA CHAR(25) -- FK
);

 -- Tabla Pago_venta
CREATE TABLE #Pago_venta (
    PAGO_VENTA_CODIGO INT PRIMARY KEY,
	VENTA_CODIGO INT, --FK
    PAGO_VENTA_IMPORTE DECIMAL(10,2),
    PAGO_VENTA_MONEDA CHAR(25), -- FK
    PAGO_VENTA_COTIZACION DECIMAL(10,2),
    PAGO_VENTA_MEDIO_PAGO CHAR(25) -- FK
);

-- Tabla Comprador
CREATE TABLE #Comprador (
    COMPRADOR_DNI INT PRIMARY KEY,
    COMPRADOR_NOMBRE VARCHAR(100),
    COMPRADOR_APELLIDO VARCHAR(100),
    COMPRADOR_FECHA_REGISTRO DATE,
    COMPRADOR_TELEFONO VARCHAR(20),
    COMPRADOR_MAIL VARCHAR(100),
    COMPRADOR_FECHA_NAC DATE
);

-- Tabla Alquiler
CREATE TABLE #Alquiler (
    ALQUILER_CODIGO INT PRIMARY KEY,
    ALQUILER_FECHA_INICIO DATE,
    ALQUILER_FECHA_FIN DATE,
	SUCURSAL_CODIGO INT,
    ALQUILER_CANT_PERIODOS INT,
    ALQUILER_DEPOSITO DECIMAL(10,2),
    ALQUILER_COMISION DECIMAL(10,2),
	TIPO_PERIODO CHAR(25), --FK
    ALQUILER_GASTOS_AVERIGUA DECIMAL(10,2),
    ALQUILER_ESTADO CHAR(25), -- FK
	ANUNCIO_CODIGO INT,	--FK
	INQUILINO_DNI INT -- FK
);

-- Tabla Inquilino
CREATE TABLE #Inquilino (
    INQUILINO_DNI INT PRIMARY KEY,
    INQUILINO_NOMBRE VARCHAR(100),
    INQUILINO_APELLIDO VARCHAR(100),
    INQUILINO_FECHA_REGISTRO DATE,
    INQUILINO_TELEFONO VARCHAR(20),
    INQUILINO_MAIL VARCHAR(100),
    INQUILINO_FECHA_NAC DATE
);

-- Tabla Detalle_importe_alquiler
CREATE TABLE #Detalle_importe_alquiler (
    DETALLE_ALQ_ID INT PRIMARY KEY,
	ALQUILER_CODIGO INT, --FK
    DETALLE_ALQ_NRO_PERIODO_INI INT,
    DETALLE_ALQ_NRO_PERIODO_FIN INT,
    DETALLE_ALQ_PRECIO DECIMAL(10,2)
);

-- Tabla Pago_alquiler
CREATE TABLE #Pago_alquiler (
    PAGO_ALQUILER_CODIGO INT PRIMARY KEY,
	ALQUILER_CODIGO INT, --FK
    PAGO_ALQUILER_FECHA DATE,
    PAGO_ALQUILER_FECHA_VENCIMIENTO DATE,
    PAGO_ALQUILER_NRO_PERIODO INT,
    PAGO_ALQUILER_DESC VARCHAR(200),
    PAGO_ALQUILER_FEC_INI DATE,
    PAGO_ALQUILER_FEC_FIN DATE,
    PAGO_ALQUILER_IMPORTE DECIMAL(10,2),
    PAGO_ALQUILER_MEDIO_PAGO CHAR(25), --FK
	DETALLE_ALQ_ID INT, --FK
);

------------------------------  TABLAS TIPIFICADAS -------------------------------------

-- Tabla Provincia
CREATE TABLE #Provincia (
    PROVINCIA CHAR(25) PRIMARY KEY,
);

-- Tabla Localidad
CREATE TABLE #Localidad (
    LOCALIDAD CHAR(25) PRIMARY KEY,
);

-- Tabla Barrio
CREATE TABLE #Barrio (
    BARRIO CHAR(25) PRIMARY KEY,
);

-- Tabla Tipo_inmueble
CREATE TABLE #Tipo_inmueble (
    TIPO_INMUEBLE CHAR(25) PRIMARY KEY,
);

-- Tabla Cant_inmuebles
CREATE TABLE #Cant_ambientes (
    CANT_AMBIENTES CHAR(25) PRIMARY KEY,
);

-- Tabla Orientacion
CREATE TABLE #Orientacion (
    ORIENTACION CHAR(25) PRIMARY KEY,
);

-- Tabla Disposicion
CREATE TABLE #Disposicion (
    DISPOSICION CHAR(25) PRIMARY KEY,
);

-- Tabla Tipo_periodo
CREATE TABLE #Tipo_periodo (
    TIPO_PERIODO CHAR(25) PRIMARY KEY,
);

-- Tabla Estado_anuncio
CREATE TABLE #Estado_anuncio (
    ESTADO_ANUNCIO CHAR(25) PRIMARY KEY,
);

-- Tabla Moneda
CREATE TABLE #Moneda (
    MONEDA CHAR(25) PRIMARY KEY,
);

-- Tabla Tipo_operacion
CREATE TABLE #Tipo_operacion (
    TIPO_OPERACION CHAR(25) PRIMARY KEY,
);

-- Tabla Medio_pago
CREATE TABLE #Medio_pago (
    MEDIO_PAGO CHAR(25) PRIMARY KEY,
);

-- Tabla Alquiler_estado
CREATE TABLE #Alquiler_estado (
    ALQUILER_ESTADO CHAR(25) PRIMARY KEY,
);


------------------------------------------------------------------------ Pruebas y comprobaciones de que es lo que tenemos que pasar en limpio  --------------------------------------------------------- 

---- seleccion personalizada para uno de los 3 casos, en este consiste en agarrar todos los anuncios y el alquiler correspondiente, para ver tambien todos los pagos hechos 
-- Es el caso 1 de 3 
SELECT * 
FROM gd_esquema.Maestra  
WHERE 
    ANUNCIO_CODIGO IS NOT NULL AND 
    AGENTE_DNI IS NOT NULL AND 
    SUCURSAL_CODIGO IS NOT NULL AND 
    ALQUILER_CODIGO IS NOT NULL AND 
    INQUILINO_DNI IS NOT NULL;
	
	-- Este caso es donde estoy seteando un inmueble con un anuncio en particular y su dueño.
-- Es el caso 2 de 3 
SELECT * 
FROM gd_esquema.Maestra  
WHERE 
    INMUEBLE_CODIGO IS NOT NULL AND 
    PROPIETARIO_DNI IS NOT NULL AND 
    ANUNCIO_CODIGO IS NOT NULL AND 
    AGENTE_DNI IS NOT NULL AND 
    SUCURSAL_CODIGO IS NOT NULL;

	-- Este caso es donde estoy seteando un anuncio con una venta, su comprador y pago venta correspondiente
-- Es el caso 3 de 3 
SELECT * 
FROM gd_esquema.Maestra  
WHERE 
    ANUNCIO_CODIGO IS NOT NULL AND 
    AGENTE_DNI IS NOT NULL AND 
    SUCURSAL_CODIGO IS NOT NULL AND 
    VENTA_CODIGO IS NOT NULL AND 
    COMPRADOR_DNI IS NOT NULL;						

------------------------------------------------------------------------          Comiendo del script sql               --------------------------------------------------------- 


	---  FILTRADO DE TODAS LAS SUCURSALES DISTINTAS
SELECT DISTINCT SUCURSAL_CODIGO, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_TELEFONO, SUCURSAL_LOCALIDAD, SUCURSAL_PROVINCIA
INTO #TempSucursal
FROM gd_esquema.Maestra
WHERE SUCURSAL_CODIGO IS NOT NULL;

SELECT * FROM #TempSucursal;

	---  FILTRADO DE TODOS LAS AGENTES DISTINTOS
SELECT DISTINCT AGENTE_DNI, AGENTE_NOMBRE, AGENTE_APELLIDO, AGENTE_MAIL, AGENTE_TELEFONO, AGENTE_FECHA_REGISTRO ,AGENTE_FECHA_NAC, SUCURSAL_CODIGO
INTO #TempAgente
FROM gd_esquema.Maestra
WHERE AGENTE_DNI IS NOT NULL AND SUCURSAL_CODIGO IS NOT NULL;

SELECT * FROM #TempAgente;

---------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------- PROPIETARIO 
INSERT INTO #Propietario(	
		PROPIETARIO_DNI,
		PROPIETARIO_NOMBRE,
		PROPIETARIO_APELLIDO,
		PROPIETARIO_FECHA_REGISTRO,
		PROPIETARIO_TELEFONO,
		PROPIETARIO_MAIL,
		PROPIETARIO_FECHA_NAC
		)
	SELECT DISTINCT m.PROPIETARIO_DNI,
					m.PROPIETARIO_NOMBRE,
					m.PROPIETARIO_APELLIDO,
					m.PROPIETARIO_FECHA_REGISTRO,
					m.PROPIETARIO_TELEFONO,
					m.PROPIETARIO_MAIL,
					m.PROPIETARIO_FECHA_NAC
	FROM gd_esquema.Maestra m
	WHERE 
		m.INMUEBLE_CODIGO IS NOT NULL AND 
		m.PROPIETARIO_DNI IS NOT NULL AND 
		m.ANUNCIO_CODIGO IS NOT NULL AND 
		m.AGENTE_DNI IS NOT NULL AND 
		m.SUCURSAL_CODIGO IS NOT NULL
		
------------------------------------------------------------------------------------------------- INMUEBLE 

--  Meto los barrios unicos a la tabla Barrio, primero desde inmueble porque son los primeros en cargarse. 
-- Luego hago lo mismo con todo lo demas, esto para poder normalizarlo 
INSERT INTO #Barrio (BARRIO)
	SELECT DISTINCT INMUEBLE_BARRIO
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_BARRIO IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Barrio b WHERE b.BARRIO = gd_esquema.Maestra.INMUEBLE_BARRIO); -- Esto para no insertar duplicados

INSERT INTO #Localidad (LOCALIDAD)
	SELECT DISTINCT INMUEBLE_BARRIO
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_BARRIO IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Localidad l WHERE l.LOCALIDAD = gd_esquema.Maestra.INMUEBLE_BARRIO);

INSERT INTO #Provincia (PROVINCIA)
	SELECT DISTINCT INMUEBLE_PROVINCIA
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_PROVINCIA IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Provincia p WHERE p.PROVINCIA = gd_esquema.Maestra.INMUEBLE_PROVINCIA);

INSERT INTO #Tipo_inmueble (TIPO_INMUEBLE)
	SELECT DISTINCT INMUEBLE_TIPO_INMUEBLE
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_TIPO_INMUEBLE IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Tipo_inmueble ti WHERE ti.TIPO_INMUEBLE = gd_esquema.Maestra.INMUEBLE_TIPO_INMUEBLE);

INSERT INTO #Cant_ambientes (CANT_AMBIENTES)
	SELECT DISTINCT INMUEBLE_CANT_AMBIENTES
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_CANT_AMBIENTES IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Cant_ambientes ca WHERE ca.CANT_AMBIENTES = gd_esquema.Maestra.INMUEBLE_CANT_AMBIENTES);

INSERT INTO #Orientacion (ORIENTACION)
	SELECT DISTINCT INMUEBLE_ORIENTACION
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_ORIENTACION IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Orientacion o WHERE o.ORIENTACION = gd_esquema.Maestra.INMUEBLE_ORIENTACION);

INSERT INTO #Disposicion (DISPOSICION)
	SELECT DISTINCT INMUEBLE_DISPOSICION
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_DISPOSICION IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Disposicion d WHERE d.DISPOSICION = gd_esquema.Maestra.INMUEBLE_DISPOSICION);

-- Inserto en la tabla Caracteristicas todas las posibilidades
INSERT INTO #Caracteristica (CARACTERISTICA)
	VALUES ('WIFI'), ('CABLE'), ('CALEFACCION'), ('GAS');

INSERT INTO #Inmueble (
    INMUEBLE_CODIGO,
    INMUEBLE_NOMBRE,
    INMUEBLE_DESCRIPCION,
    INMUEBLE_DIRECCION,
    INMUEBLE_SUPERFICIETOTAL,
    INMUEBLE_ANTIGUEDAD,
    INMUEBLE_EXPESAS,
    INMUEBLE_BARRIO, -- FK
    INMUEBLE_LOCALIDAD, -- FK
    INMUEBLE_PROVINCIA, -- FK
    INMUEBLE_TIPO_INMUEBLE, -- FK
    INMUEBLE_CANT_AMBIENTES, -- FK
    INMUEBLE_ORIENTACION, -- FK
    INMUEBLE_DISPOSICION, -- FK
    PROPIETARIO_DNI --FK
	)
	SELECT DISTINCT m.INMUEBLE_CODIGO,
					m.INMUEBLE_NOMBRE,
					m.INMUEBLE_DESCRIPCION,
					m.INMUEBLE_DIRECCION,
					m.INMUEBLE_SUPERFICIETOTAL,
					m.INMUEBLE_ANTIGUEDAD,
					m.INMUEBLE_EXPESAS,
					m.INMUEBLE_BARRIO, 
					m.INMUEBLE_LOCALIDAD,
					m.INMUEBLE_PROVINCIA,
					m.INMUEBLE_TIPO_INMUEBLE,
					m.INMUEBLE_CANT_AMBIENTES,
					m.INMUEBLE_ORIENTACION,
					m.INMUEBLE_DISPOSICION,
					m.PROPIETARIO_DNI
	FROM 
		gd_esquema.Maestra m
	WHERE 
		m.INMUEBLE_CODIGO IS NOT NULL AND 
		m.PROPIETARIO_DNI IS NOT NULL AND 
		m.ANUNCIO_CODIGO IS NOT NULL AND 
		m.AGENTE_DNI IS NOT NULL AND 
		m.SUCURSAL_CODIGO IS NOT NULL;

-- Procedo a insertarle las caracteristicas correspondientes a cada inmueble
INSERT INTO #Inmueble_caracteristica (INMUEBLE_ID, CARACTERISTICA)
	SELECT INMUEBLE_CODIGO, 'WIFI'
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_CARACTERISTICA_WIFI = 1;

INSERT INTO #Inmueble_caracteristica (INMUEBLE_ID, CARACTERISTICA)
	SELECT INMUEBLE_CODIGO, 'CABLE'
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_CARACTERISTICA_CABLE = 1;
	
INSERT INTO #Inmueble_caracteristica (INMUEBLE_ID, CARACTERISTICA)
	SELECT INMUEBLE_CODIGO, 'CALEFACCION'
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_CARACTERISTICA_CALEFACCION = 1;

INSERT INTO #Inmueble_caracteristica (INMUEBLE_ID, CARACTERISTICA)
	SELECT INMUEBLE_CODIGO, 'GAS'
	FROM gd_esquema.Maestra
	WHERE INMUEBLE_CARACTERISTICA_GAS = 1;

------------------------------------------------------------------------------------------------- SUCURSAL 

INSERT INTO #Provincia (PROVINCIA)
	SELECT DISTINCT SUCURSAL_PROVINCIA
	FROM gd_esquema.Maestra
	WHERE SUCURSAL_PROVINCIA IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Provincia p WHERE p.PROVINCIA = gd_esquema.Maestra.SUCURSAL_PROVINCIA);

INSERT INTO #Localidad (LOCALIDAD)
	SELECT DISTINCT SUCURSAL_LOCALIDAD
	FROM gd_esquema.Maestra
	WHERE SUCURSAL_LOCALIDAD IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Localidad l WHERE l.LOCALIDAD = gd_esquema.Maestra.SUCURSAL_LOCALIDAD);

INSERT INTO #Sucursal (
		SUCURSAL_CODIGO,
		SUCURSAL_NOMBRE,
		SUCURSAL_DIRECCION,
		SUCURSAL_TELEFONO,
		SUCURSAL_LOCALIDAD,
		SUCURSAL_PROVINCIA
	)
	SELECT DISTINCT m.SUCURSAL_CODIGO,
					m.SUCURSAL_NOMBRE,
					m.SUCURSAL_DIRECCION,
					m.SUCURSAL_TELEFONO,
					m.SUCURSAL_LOCALIDAD,
					m.SUCURSAL_PROVINCIA
	FROM 
	gd_esquema.Maestra m
	WHERE
		m.INMUEBLE_CODIGO IS NOT NULL AND 
		m.PROPIETARIO_DNI IS NOT NULL AND 
		m.ANUNCIO_CODIGO IS NOT NULL AND 
		m.AGENTE_DNI IS NOT NULL AND 
		m.SUCURSAL_CODIGO IS NOT NULL;

------------------------------------------------------------------------------------------------- AGENTE

INSERT INTO #Agente (
		AGENTE_DNI,
		AGENTE_NOMBRE,
		AGENTE_APELLIDO,
		AGENTE_TELEFONO,
		AGENTE_FECHA_REGISTRO,
		AGENTE_MAIL,
		AGENTE_FECHA_NAC,
		SUCURSAL_CODIGO
	)
	SELECT DISTINCT m.AGENTE_DNI,
					m.AGENTE_NOMBRE,
					m.AGENTE_APELLIDO,
					m.AGENTE_TELEFONO,
					m.AGENTE_FECHA_REGISTRO,
					m.AGENTE_MAIL,
					m.AGENTE_FECHA_NAC,
					m.SUCURSAL_CODIGO
	FROM 
	gd_esquema.Maestra m
	WHERE
		m.INMUEBLE_CODIGO IS NOT NULL AND 
		m.PROPIETARIO_DNI IS NOT NULL AND 
		m.ANUNCIO_CODIGO IS NOT NULL AND 
		m.AGENTE_DNI IS NOT NULL AND 
		m.SUCURSAL_CODIGO IS NOT NULL;
	
------------------------------------------------------------------------------------------------- ANUNCIO


INSERT INTO #Tipo_periodo (TIPO_PERIODO)
	SELECT DISTINCT ANUNCIO_TIPO_PERIODO
	FROM gd_esquema.Maestra
	WHERE ANUNCIO_TIPO_PERIODO IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Tipo_periodo tp WHERE tp.TIPO_PERIODO = gd_esquema.Maestra.ANUNCIO_TIPO_PERIODO);

		
INSERT INTO #Estado_anuncio (ESTADO_ANUNCIO)
	SELECT DISTINCT ANUNCIO_ESTADO
	FROM gd_esquema.Maestra
	WHERE ANUNCIO_ESTADO IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Estado_anuncio ea WHERE ea.ESTADO_ANUNCIO = gd_esquema.Maestra.ANUNCIO_ESTADO);

		
INSERT INTO #Moneda (MONEDA)
	SELECT DISTINCT ANUNCIO_MONEDA
	FROM gd_esquema.Maestra
	WHERE ANUNCIO_MONEDA IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Moneda m WHERE m.MONEDA = gd_esquema.Maestra.ANUNCIO_MONEDA);

		
INSERT INTO #Tipo_operacion (TIPO_OPERACION)
	SELECT DISTINCT ANUNCIO_TIPO_OPERACION
	FROM gd_esquema.Maestra
	WHERE ANUNCIO_TIPO_OPERACION IS NOT NULL AND 
		NOT EXISTS (SELECT 1 FROM #Tipo_operacion t WHERE t.TIPO_OPERACION = gd_esquema.Maestra.ANUNCIO_TIPO_OPERACION);

INSERT INTO #Anuncio (
		ANUNCIO_CODIGO,
		ANUNCIO_FECHA_PUBLICACION,
		ANUNCIO_PRECIO_PUBLICADO,
		ANUNCIO_COSTO_ANUNCIO,
		ANUNCIO_FECHA_FINALIZACION,
		ANUNCIO_TIPO_OPERACION,
		ANUNCIO_MONEDA,
		ANUNCIO_ESTADO,
		ANUNCIO_TIPO_PERIODO,
		ANUNCIO_AGENTE,
		INMUEBLE_CODIGO
	)
	SELECT DISTINCT m.ANUNCIO_CODIGO,
					m.ANUNCIO_FECHA_PUBLICACION,
					m.ANUNCIO_PRECIO_PUBLICADO,
					m.ANUNCIO_COSTO_ANUNCIO,
					m.ANUNCIO_FECHA_FINALIZACION,
					m.ANUNCIO_TIPO_OPERACION,
					m.ANUNCIO_MONEDA,
					m.ANUNCIO_ESTADO,
					m.ANUNCIO_TIPO_PERIODO,
					m.AGENTE_DNI,
					m.INMUEBLE_CODIGO
	FROM 
	gd_esquema.Maestra m
	WHERE
		m.INMUEBLE_CODIGO IS NOT NULL AND 
		m.PROPIETARIO_DNI IS NOT NULL AND 
		m.ANUNCIO_CODIGO IS NOT NULL AND 
		m.AGENTE_DNI IS NOT NULL AND 
		m.SUCURSAL_CODIGO IS NOT NULL;
