CREATE SCHEMA DATA_TEAM
GO
CREATE TABLE DATA_TEAM.Inmueble (
	INMUEBLE_ID INT IDENTITY(1,1) PRIMARY KEY,
    INMUEBLE_CODIGO NUMERIC(18,0),
    INMUEBLE_NOMBRE NVARCHAR(100),
    INMUEBLE_DESCRIPCION NVARCHAR(100),
    INMUEBLE_DIRECCION NVARCHAR(100),
    INMUEBLE_SUPERFICIETOTAL NUMERIC(18,2),
    INMUEBLE_ANTIGUEDAD NUMERIC(18,0),
    INMUEBLE_EXPESAS NUMERIC(18,2),
    INMUEBLE_BARRIO NVARCHAR(100), -- FK
    INMUEBLE_LOCALIDAD NVARCHAR(100), -- FK
    INMUEBLE_PROVINCIA NVARCHAR(100), -- FK
    INMUEBLE_TIPO_INMUEBLE NVARCHAR(100), -- FK
    INMUEBLE_CANT_AMBIENTES NVARCHAR(100), -- FK
    INMUEBLE_ORIENTACION NVARCHAR(100), -- FK
    INMUEBLE_DISPOSICION NVARCHAR(100), -- FK
    INMUEBLE_ESTADO NVARCHAR(100) -- FK
);

CREATE TABLE DATA_TEAM.Inmueble_Caracteristica (
	INMUEBLE_CARACTERISTICA_INMUEBLE INT PRIMARY KEY,
	INMUEBLE_CARACTERISTICA_DESCRIPCION VARCHAR(100)
)

-- Tabla Propietario
CREATE TABLE DATA_TEAM.Propietario (
    PROPIETARIO_ID INT PRIMARY KEY,
    PROPIETARIO_NOMBRE NVARCHAR(100),
    PROPIETARIO_APELLIDO NVARCHAR(100),
    PROPIETARIO_DNI NUMERIC(18,0),
    PROPIETARIO_FECHA_REGISTRO DATETIME,
    PROPIETARIO_TELEFONO NUMERIC(18,0),
    PROPIETARIO_MAIL NVARCHAR(255),
    PROPIETARIO_FECHA_NAC DATETIME
);

-- Tabla Anuncio
CREATE TABLE DATA_TEAM.Anuncio (
    ANUNCIO_CODIGO NUMERIC(19,0) PRIMARY KEY,
    ANUNCIO_FECHA_PUBLICACION DATETIME,
    ANUNCIO_PRECIO_PUBLICADO NUMERIC(18,2),
    ANUNCIO_COSTO_ANUNCIO NUMERIC(18,2),
    ANUNCIO_FECHA_FINALIZACION DATETIME,
    ANUNCIO_TIPO_OPERACION NVARCHAR(100), -- FK
    ANUNCIO_MONEDA NVARCHAR(100), -- FK
    ANUNCIO_ESTADO NVARCHAR(100), -- FK
    ANUNCIO_TIPO_PERIODO NVARCHAR(100) -- FK
);

-- Tabla Agente
CREATE TABLE DATA_TEAM.Agente (
    AGENTE_ID INT PRIMARY KEY,
    AGENTE_NOMBRE NVARCHAR(100),
    AGENTE_APELLIDO NVARCHAR(100),
    AGENTE_DNI NUMERIC(18,0),
    AGENTE_FECHA_REGISTRO DATETIME,
    AGENTE_TELEFONO NUMERIC(18,0),
    AGENTE_MAIL NVARCHAR(100),
    AGENTE_FECHA_NAC DATETIME
);

-- Tabla Sucursal
CREATE TABLE DATA_TEAM.Sucursal (
    SUCURSAL_CODIGO NUMERIC(18,0) PRIMARY KEY,
    SUCURSAL_NOMBRE NVARCHAR(100),
    SUCURSAL_DIRECCION NVARCHAR(100),
    SUCURSAL_TELEFONO NVARCHAR(100),
    SUCURSAL_LOCALIDAD NVARCHAR(100), -- FK
    SUCURSAL_PROVINCIA NVARCHAR(100) -- FK
);

CREATE TABLE DATA_TEAM.Venta (
    VENTA_CODIGO NUMERIC(18,0) PRIMARY KEY,
    VENTA_FECHA DATETIME,
    VENTA_PRECIO_VENTA NUMERIC(18,2),
    VENTA_COMISION NUMERIC(18,2),
    VENTA_MONEDA NVARCHAR(100) -- FK
);

-- Tabla Comprador
CREATE TABLE DATA_TEAM.Comprador (
    COMPRADOR_ID INT PRIMARY KEY,
    COMPRADOR_NOMBRE NVARCHAR(100),
    COMPRADOR_APELLIDO NVARCHAR(100),
    COMPRADOR_DNI NUMERIC(18,0),
    COMPRADOR_FECHA_REGISTRO DATETIME,
    COMPRADOR_TELEFONO NUMERIC(18,0),
    COMPRADOR_MAIL NVARCHAR(100),
    COMPRADOR_FECHA_NAC DATETIME
);

-- Tabla Inquilino
CREATE TABLE DATA_TEAM.Inquilino (
    INQUILINO_ID INT PRIMARY KEY,
    INQUILINO_NOMBRE NVARCHAR(100),
    INQUILINO_APELLIDO NVARCHAR(100),
    INQUILINO_DNI NUMERIC(18,0),
    INQUILINO_FECHA_REGISTRO DATETIME,
    INQUILINO_TELEFONO NUMERIC(18,0),
    INQUILINO_MAIL NVARCHAR(100),
    INQUILINO_FECHA_NAC DATETIME
);

-- Tabla Alquiler
CREATE TABLE DATA_TEAM.Alquiler (
    ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY,
    ALQUILER_FECHA_INICIO DATETIME,
    ALQUILER_FECHA_FIN DATETIME,
    ALQUILER_CANT_PERIODOS NUMERIC(18,0),
    ALQUILER_DEPOSITO NUMERIC(18,2),
    ALQUILER_COMISION NUMERIC(18,2),
    ALQUILER_GASTOS_AVERIGUA NUMERIC(18,2),
    ALQUILER_ESTADO NVARCHAR(100) -- FK
);

-- Tabla Pago_alquiler
CREATE TABLE DATA_TEAM.Pago_alquiler (
    PAGO_ALQUILER_CODIGO NUMERIC(18,0) PRIMARY KEY,
    PAGO_ALQUILER_FECHA DATETIME,
    PAGO_ALQUILER_FECHA_VENCIMIENTO DATETIME,
    PAGO_ALQUILER_NRO_PERIODO NUMERIC(18,0),
    PAGO_ALQUILER_DESC NVARCHAR(100),
    PAGO_ALQUILER_FEC_INI DATETIME,
    PAGO_ALQUILER_FEC_FIN DATETIME,
    PAGO_ALQUILER_IMPORTE NUMERIC(18,2),
    PAGO_ALQUILER_MEDIO_PAGO NVARCHAR(100)
);

-- Tabla Detalle_importe_alquiler
CREATE TABLE DATA_TEAM.Detalle_Alquiler (
    DETALLE_ALQ_ID INT IDENTITY(1,1) PRIMARY KEY,
    NRO_PERIODO_INI NUMERIC(18,0),
    NRO_PERIODO_FIN NUMERIC(18,0),
    PRECIO NUMERIC(18,2)
);

-- Tabla Pago_venta
CREATE TABLE DATA_TEAM.Pago_venta (
    PAGO_VENTA_ID INT PRIMARY KEY,
    PAGO_VENTA_IMPORTE NUMERIC(18,2),
    PAGO_VENTA_MONEDA NVARCHAR(100), -- FK
    PAGO_VENTA_COTIZACION NUMERIC(18,2),
    PAGO_VENTA_MEDIO_PAGO NVARCHAR(100) -- FK
);

INSERT INTO DATA_TEAM.Inmueble SELECT INMUEBLE_CODIGO, 
INMUEBLE_NOMBRE, 
INMUEBLE_DESCRIPCION, 
INMUEBLE_DIRECCION, 
INMUEBLE_SUPERFICIETOTAL, 
INMUEBLE_ANTIGUEDAD, 
INMUEBLE_EXPESAS,
INMUEBLE_BARRIO,
INMUEBLE_LOCALIDAD,
INMUEBLE_PROVINCIA,
INMUEBLE_TIPO_INMUEBLE,
INMUEBLE_CANT_AMBIENTES,
INMUEBLE_ORIENTACION,
INMUEBLE_DISPOSICION,
INMUEBLE_ESTADO
FROM gd_esquema.Maestra
WHERE INMUEBLE_CODIGO IS NOT NULL

SELECT * FROM DATA_TEAM.Inmueble ORDER BY INMUEBLE_CODIGO